//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Insights.SummaryGenerator.InsightGenerators.Configuration.EvaluationRules.PolicyMixed {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PolicyMixedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PolicyMixedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Insights.SummaryGenerator.InsightGenerators.Configuration.EvaluationRul" +
                            "es.PolicyMixed.PolicyMixedResources", typeof(PolicyMixedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking at your DMARC reporting in the last 30 days, {0}% of your emails are passing SPF and DKIM checks.
        ///
        ///Note that Mail Check only detects systems to configure that contribute &gt; 10 emails and &gt; 1% of your traffic per month. You can [review your DMARC reporting]({1}/app/domain-security/{2}/custom/{3:yyyy-MM-dd}/{4:yyyy-MM-dd}/false/emailtraffic) to check if there are further lower volumes systems that might need configuring.
        ///
        ///For further information on how to implement this change, [refer to our guidan [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PolicyMixedInfoMarkdown {
            get {
                return ResourceManager.GetString("PolicyMixedInfoMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are moving (or have moved recently) to a stronger DMARC policy, and Mail Check did not find any email sending systems that need configuring with SPF/ DKIM..
        /// </summary>
        public static string PolicyMixedInfoTitle {
            get {
                return ResourceManager.GetString("PolicyMixedInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are moving (or have moved recently) to a stronger DMARC policy, but you still have SPF/DKIM configuration issues with {0} sending systems.
        /// </summary>
        public static string PolicyMixedWarningTitle {
            get {
                return ResourceManager.GetString("PolicyMixedWarningTitle", resourceCulture);
            }
        }
    }
}
