//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Insights.SummaryGenerator.InsightGenerators.Configuration.EvaluationRules.PolicyQuarReject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PolicyQuarRejectRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PolicyQuarRejectRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Insights.SummaryGenerator.InsightGenerators.Configuration.EvaluationRul" +
                            "es.PolicyQuarReject.PolicyQuarRejectRes", typeof(PolicyQuarRejectRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Check has not detected any systems that need configuring with SPF and DKIM
        ///
        ///Mail Check won&apos;t have detected any systems with low volumes, contributing &lt; 10 emails or &lt; 1% of your overall email traffic per month.
        ///
        ///You may want to review your DMARC reporting to check if there are any further systems that need configuring.
        ///
        ///[Review email traffic marked as {3}]({4}/app/domain-security/{0}/custom/{1}/{2}/false/emailtraffic?categoryFilter={3}).
        /// </summary>
        internal static string PolicyQrSuccessMarkdown {
            get {
                return ResourceManager.GetString("PolicyQrSuccessMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Check has not detected any systems that need configuring with SPF and DKIM.
        /// </summary>
        internal static string PolicyQrSuccessText {
            get {
                return ResourceManager.GetString("PolicyQrSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a DMARC policy of quarantine or reject, which means emails from {0} that fail SPF and DKIM will be sent to Junk or blocked altogether.
        ///
        ///However, Mail Check detected {1} system(s) that might be legitimate that are failing SPF and DKIM:
        ///
        ///{2}
        ///
        ///[Go to Email Traffic page for {0}]({5}/app/domain-security/{0}/custom/{3:yyyy-MM-dd}/{4:yyyy-MM-dd}/false/emailtraffic)
        ///
        ///You either need to configure the system(s) with SPF and/or DKIM, or if the system is not approved for use in your organisation, you w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolicyQrWarningMarkdown {
            get {
                return ResourceManager.GetString("PolicyQrWarningMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Check has detected {0} system(s) that might be legitimate for you to review that is failing SPF and DKIM, and therefore being sent to Junk or blocked altogether.
        /// </summary>
        internal static string PolicyQrWarningText {
            get {
                return ResourceManager.GetString("PolicyQrWarningText", resourceCulture);
            }
        }
    }
}
