//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Insights.DataSaver.DataSavers.Subdomains {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubdomainDataSaverResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubdomainDataSaverResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Insights.DataSaver.DataSavers.Subdomains.SubdomainDataSaverResources", typeof(SubdomainDataSaverResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `insights`.`aggregated_subdomains`
        ///  (`domain`,
        ///  `reverse_domain`,
        ///  `effective_date`,
        ///  `all_traffic_count`,
        ///  `dkim_or_spf_failed_none_count`,
        ///  `dkim_or_spf_failed_quarantine_or_reject_count`,
        ///  `dkim_and_spf_failed_none_count`,
        ///  `dkim_and_spf_failed_quarantine_or_reject_count`,
        ///  `blocklist_or_failed_reverse_dns_count`,
        ///  `record_count`)
        ///SELECT
        ///  @Domain,
        ///  @ReverseDomain,
        ///  @EffectiveDate,
        ///  @AllTrafficCount,
        ///  @DkimOrSpfFailedNoneCount,
        ///  @DkimOrSpfFailedQuarantineOrReje [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InsertSubdomainData {
            get {
                return ResourceManager.GetString("InsertSubdomainData", resourceCulture);
            }
        }
    }
}
