//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Insights.SummaryGenerator.InsightGenerators.Configuration.EvaluationRules.PolicyNone {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PolicyNoneResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PolicyNoneResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Insights.SummaryGenerator.InsightGenerators.Configuration.EvaluationRul" +
                            "es.PolicyNone.PolicyNoneResources", typeof(PolicyNoneResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking at your DMARC reporting in the last 30 days, {0}% of your emails are passing DMARC. Note this applies to emails from {1} but not sub-domains (see separate DMARC Insights).
        ///
        ///**You should start considering how and when you will move to a DMARC policy of ‘Quarantine’**
        ///
        ///A DMARC policy of quarantine will ensure that malicious spoofed emails that fail SPF and DKIM checks are sent to Junk folders.
        ///
        ///You should consider the following:
        ///
        ///- Are all your email sending systems* on {1} configured with SPF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PolicyNoneInfoMarkdown {
            get {
                return ResourceManager.GetString("PolicyNoneInfoMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Check has identified that {0}% of your emails are passing DMARC, so you are ready (or nearly ready) to upgrade your DMARC policy to &apos;quarantine&apos;.
        /// </summary>
        public static string PolicyNoneInfoText {
            get {
                return ResourceManager.GetString("PolicyNoneInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Check identified that {0}% of your email traffic is failing SPF and DKIM checks, related to configuration issues with {1} email sending system(s).
        /// </summary>
        public static string PolicyNoneWarningTitle {
            get {
                return ResourceManager.GetString("PolicyNoneWarningTitle", resourceCulture);
            }
        }
    }
}
