//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Insights.DataSaver.DataSavers.Abuse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AbuseDataSaverResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AbuseDataSaverResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Insights.DataSaver.DataSavers.Abuse.AbuseDataSaverResources", typeof(AbuseDataSaverResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///INSERT INTO `insights`.`aggregated_abuse`
        ///  (`domain`, `reverse_domain`, `effective_date`, `count`, `flagged`, `p`, `pct`, `record_count`)
        ///SELECT
        ///  @domain, @ReverseDomain, @EffectiveDate, @count, @flagged, @p, @pct, 1
        ///WHERE NOT EXISTS
        ///(  
        ///  SELECT 1 FROM `insights`.`aggregate_report_record_enriched` 
        ///  WHERE `reverse_domain` = @ReverseDomain AND `effective_date` = @EffectiveDate AND `record_id` = @RecordId
        ///  LIMIT 1
        ///)
        ///ON DUPLICATE KEY UPDATE 
        ///  flagged=flagged + @flagged,
        ///  count=count + @cou [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InsertAbuseData {
            get {
                return ResourceManager.GetString("InsertAbuseData", resourceCulture);
            }
        }
    }
}
