//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Insights.SummaryGenerator.InsightGenerators.Subdomains.EvaluationRules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubdomainsRulesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubdomainsRulesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Insights.SummaryGenerator.InsightGenerators.Subdomains.EvaluationRules." +
                            "SubdomainsRulesResource", typeof(SubdomainsRulesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the last 30 days, Mail Check saw {0} subdomains of {1} that had a DMARC policy of &apos;none&apos;. Some or all of these have SPF and DKIM configuration issues..
        /// </summary>
        public static string DispositionNoneRule {
            get {
                return ResourceManager.GetString("DispositionNoneRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the last 30 days, Mail Check saw {0} subdomains of {1} that were well configured with a strong DMARC policy of quarantine or reject..
        /// </summary>
        public static string DispositionQuarantineOrRejectLessThan5Percent {
            get {
                return ResourceManager.GetString("DispositionQuarantineOrRejectLessThan5Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the last 30 days, Mail Check saw {0} subdomains of {1} that were well configured with a strong DMARC policy of quarantine or reject, but with possible legitimate systems that need configuring with SPF and DKIM..
        /// </summary>
        public static string DispositionQuarantineOrRejectMoreThan5Percent {
            get {
                return ResourceManager.GetString("DispositionQuarantineOrRejectMoreThan5Percent", resourceCulture);
            }
        }
    }
}
