//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Insights.SummaryGenerator.InsightGenerators.Subdomains.EvaluationRules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubdomainsRulesMarkdownResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubdomainsRulesMarkdownResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Insights.SummaryGenerator.InsightGenerators.Subdomains.EvaluationRules." +
                            "SubdomainsRulesMarkdownResource", typeof(SubdomainsRulesMarkdownResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///**Note:** This list only contains subdomains with &gt; 10 emails in the last 30 days.
        /// </summary>
        public static string DispositionNone {
            get {
                return ResourceManager.GetString("DispositionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///**Note:** This list only contains subdomains with &gt; 10 emails in the last 30 days, with &lt;5% failing DMARC.
        /// </summary>
        public static string DispositionQuarantineOrRejectLessThan5Percent {
            get {
                return ResourceManager.GetString("DispositionQuarantineOrRejectLessThan5Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///**Note:** This list only contains subdomains with &gt; 10 emails in the last 30 days, with &gt;5% failing DMARC.
        /// </summary>
        public static string DispositionQuarantineOrRejectMoreThan5Percent {
            get {
                return ResourceManager.GetString("DispositionQuarantineOrRejectMoreThan5Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and a further {0} subdomains.
        /// </summary>
        public static string MoreThan150RecordMessage {
            get {
                return ResourceManager.GetString("MoreThan150RecordMessage", resourceCulture);
            }
        }
    }
}
